spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hackathon
    username: hackathon
    password: hackathon
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  #servlet:
    #multipart:
    #max-file-size: 10GB
    #max-request-size: 10GB
